Update CD

diff --git a/CD b/CD
--- a/CD
+++ b/CD
@@ -1,30 +1,46 @@
 pipeline {
     agent any
 
-    tools {
-        jdk 'jdk17'
-        nodejs 'node16'
+    environment {
+        REMOTE_HOST = "ubuntu@3.85.232.84"
+        IMAGE_NAME  = "shakirdocker/starbucks"
+        IMAGE_TAG   = "latest"
     }
 
     stages {
 
-        stage("Deploy to Container") {
+        stage("Deploy to Remote Server") {
             steps {
-                script {
-                    // Stop & remove old container (if exists)
-                    sh """
-                    if [ \$(docker ps -aq -f name=starbucks) ]; then
-                        docker rm -f starbucks
-                    fi
-                    """
+                sshagent(credentials: ['ec2-ssh']) {
 
-                    // Run latest container
                     sh """
-                    docker run -d --name starbucks -p 3000:3000 shakirdocker/starbucks:latest
+                    ssh -o StrictHostKeyChecking=no ${REMOTE_HOST} '
+
+                        docker pull ${IMAGE_NAME}:${IMAGE_TAG}
+
+                        docker stop starbucks || true
+
+                        docker rm starbucks || true
+
+                        docker run -d \
+                            --name starbucks \
+                            --restart unless-stopped \
+                            -p 3000:3000 \
+                            ${IMAGE_NAME}:${IMAGE_TAG}
+                    '
                     """
                 }
             }
         }
+    }
 
+    post {
+        success {
+            echo "Application deployed successfully."
+        }
+
+        failure {
+            echo "Deployment failed."
+        }
     }
 }
